spring.application.name=demo

# 1. Server Configuration
server.port=8080

# 2. Database Configuration (e.g., PostgreSQL or MySQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Prueba1
#spring.datasource.driver-class-name=org.postgresql.Driver 

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

#Configuracion para que la BD se actualice sola.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
