spring.application.name=proyecto-pm-2026

# 1. Server Configuration
server.port=8080

# 2. Database Configuration (e.g., PostgreSQL or MySQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}